# Site settings
title: "Tudor Donca"
author: "Tudor Donca"
description: "This is a collection of writeups detailing my studies in the fields of robotics and AI."
keywords: "Tudor Donca, Robotics, Software Engineering, Programming, Machine-Learning, Artificial Intelligence, Statistics, Networking"
biography: "I am a Computer Science and Engineering student at <a href='https://samueli.ucla.edu/'>UCLA</a>, and a Robotics Research Assistant at <a href='http://vcla.stat.ucla.edu/'>VCLA</a>. Here you can find my <a href='/assets/resume.pdf'>Résumé</a>."
colophon: "© 2018 by Tudor Donca.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://tudordonca.com"

twitter_username: 
github_username: tdonca
linkedin_username: tgdonca
facebook_username: tudor.donca.3
google-analytics: 

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

plugins: 
  - jekyll-redirect-from